
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp____src_include_dbus_org_freedesktop_NetworkManager_WifiP2PPeer_hpp__proxy__H__
#define __sdbuscpp____src_include_dbus_org_freedesktop_NetworkManager_WifiP2PPeer_hpp__proxy__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace org {
namespace freedesktop {
namespace NetworkManager {

class WifiP2PPeer_proxy
{
public:
    static constexpr const char* INTERFACE_NAME = "org.freedesktop.NetworkManager.WifiP2PPeer";

protected:
    WifiP2PPeer_proxy(sdbus::IProxy& proxy)
        : m_proxy(proxy)
    {
    }

    WifiP2PPeer_proxy(const WifiP2PPeer_proxy&) = delete;
    WifiP2PPeer_proxy& operator=(const WifiP2PPeer_proxy&) = delete;
    WifiP2PPeer_proxy(WifiP2PPeer_proxy&&) = delete;
    WifiP2PPeer_proxy& operator=(WifiP2PPeer_proxy&&) = delete;

    ~WifiP2PPeer_proxy() = default;

    void registerProxy()
    {
    }

public:
    std::string Name()
    {
        return m_proxy.getProperty("Name").onInterface(INTERFACE_NAME).get<std::string>();
    }

    uint32_t Flags()
    {
        return m_proxy.getProperty("Flags").onInterface(INTERFACE_NAME).get<uint32_t>();
    }

    std::string Manufacturer()
    {
        return m_proxy.getProperty("Manufacturer").onInterface(INTERFACE_NAME).get<std::string>();
    }

    std::string Model()
    {
        return m_proxy.getProperty("Model").onInterface(INTERFACE_NAME).get<std::string>();
    }

    std::string ModelNumber()
    {
        return m_proxy.getProperty("ModelNumber").onInterface(INTERFACE_NAME).get<std::string>();
    }

    std::string Serial()
    {
        return m_proxy.getProperty("Serial").onInterface(INTERFACE_NAME).get<std::string>();
    }

    std::vector<uint8_t> WfdIEs()
    {
        return m_proxy.getProperty("WfdIEs").onInterface(INTERFACE_NAME).get<std::vector<uint8_t>>();
    }

    std::string HwAddress()
    {
        return m_proxy.getProperty("HwAddress").onInterface(INTERFACE_NAME).get<std::string>();
    }

    uint8_t Strength()
    {
        return m_proxy.getProperty("Strength").onInterface(INTERFACE_NAME).get<uint8_t>();
    }

    int32_t LastSeen()
    {
        return m_proxy.getProperty("LastSeen").onInterface(INTERFACE_NAME).get<int32_t>();
    }

private:
    sdbus::IProxy& m_proxy;
};

}}} // namespaces

#endif
