
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp____src_include_dbus_org_freedesktop_NetworkManager_Device_WifiP2P_hpp__proxy__H__
#define __sdbuscpp____src_include_dbus_org_freedesktop_NetworkManager_Device_WifiP2P_hpp__proxy__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace org {
namespace freedesktop {
namespace NetworkManager {
namespace Device {

class WifiP2P_proxy
{
public:
    static constexpr const char* INTERFACE_NAME = "org.freedesktop.NetworkManager.Device.WifiP2P";

protected:
    WifiP2P_proxy(sdbus::IProxy& proxy)
        : m_proxy(proxy)
    {
    }

    WifiP2P_proxy(const WifiP2P_proxy&) = delete;
    WifiP2P_proxy& operator=(const WifiP2P_proxy&) = delete;
    WifiP2P_proxy(WifiP2P_proxy&&) = delete;
    WifiP2P_proxy& operator=(WifiP2P_proxy&&) = delete;

    ~WifiP2P_proxy() = default;

    void registerProxy()
    {
        m_proxy.uponSignal("PeerAdded").onInterface(INTERFACE_NAME).call([this](const sdbus::ObjectPath& peer){ this->onPeerAdded(peer); });
        m_proxy.uponSignal("PeerRemoved").onInterface(INTERFACE_NAME).call([this](const sdbus::ObjectPath& peer){ this->onPeerRemoved(peer); });
    }

    virtual void onPeerAdded(const sdbus::ObjectPath& peer) = 0;
    virtual void onPeerRemoved(const sdbus::ObjectPath& peer) = 0;

public:
    void StartFind(const std::map<std::string, sdbus::Variant>& options)
    {
        m_proxy.callMethod("StartFind").onInterface(INTERFACE_NAME).withArguments(options);
    }

    void StopFind()
    {
        m_proxy.callMethod("StopFind").onInterface(INTERFACE_NAME);
    }

public:
    std::string HwAddress()
    {
        return m_proxy.getProperty("HwAddress").onInterface(INTERFACE_NAME).get<std::string>();
    }

    std::vector<sdbus::ObjectPath> Peers()
    {
        return m_proxy.getProperty("Peers").onInterface(INTERFACE_NAME).get<std::vector<sdbus::ObjectPath>>();
    }

private:
    sdbus::IProxy& m_proxy;
};

}}}} // namespaces

#endif
