
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp____src_include_dbus_org_freedesktop_NetworkManager_DHCP6Config_hpp__proxy__H__
#define __sdbuscpp____src_include_dbus_org_freedesktop_NetworkManager_DHCP6Config_hpp__proxy__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace org {
namespace freedesktop {
namespace NetworkManager {

class DHCP6Config_proxy
{
public:
    static constexpr const char* INTERFACE_NAME = "org.freedesktop.NetworkManager.DHCP6Config";

protected:
    DHCP6Config_proxy(sdbus::IProxy& proxy)
        : m_proxy(proxy)
    {
    }

    DHCP6Config_proxy(const DHCP6Config_proxy&) = delete;
    DHCP6Config_proxy& operator=(const DHCP6Config_proxy&) = delete;
    DHCP6Config_proxy(DHCP6Config_proxy&&) = delete;
    DHCP6Config_proxy& operator=(DHCP6Config_proxy&&) = delete;

    ~DHCP6Config_proxy() = default;

    void registerProxy()
    {
    }

public:
    std::map<std::string, sdbus::Variant> Options()
    {
        return m_proxy.getProperty("Options").onInterface(INTERFACE_NAME).get<std::map<std::string, sdbus::Variant>>();
    }

private:
    sdbus::IProxy& m_proxy;
};

}}} // namespaces

#endif
