
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp__dbus_hpp_org_freedesktop_NetworkManager_DnsManager_hpp__proxy__H__
#define __sdbuscpp__dbus_hpp_org_freedesktop_NetworkManager_DnsManager_hpp__proxy__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace org {
namespace freedesktop {
namespace NetworkManager {

class DnsManager_proxy
{
public:
    static constexpr const char* INTERFACE_NAME = "org.freedesktop.NetworkManager.DnsManager";

protected:
    DnsManager_proxy(sdbus::IProxy& proxy)
        : proxy_(proxy)
    {
    }

    ~DnsManager_proxy() = default;

public:
    std::string Mode()
    {
        return proxy_.getProperty("Mode").onInterface(INTERFACE_NAME);
    }

    std::string RcManager()
    {
        return proxy_.getProperty("RcManager").onInterface(INTERFACE_NAME);
    }

    std::vector<std::map<std::string, sdbus::Variant>> Configuration()
    {
        return proxy_.getProperty("Configuration").onInterface(INTERFACE_NAME);
    }

private:
    sdbus::IProxy& proxy_;
};

}}} // namespaces

#endif
