
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp__dbus_hpp_org_freedesktop_NetworkManager_Device_Wired_hpp__proxy__H__
#define __sdbuscpp__dbus_hpp_org_freedesktop_NetworkManager_Device_Wired_hpp__proxy__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace org {
namespace freedesktop {
namespace NetworkManager {
namespace Device {

class Wired_proxy
{
public:
    static constexpr const char* INTERFACE_NAME = "org.freedesktop.NetworkManager.Device.Wired";

protected:
    Wired_proxy(sdbus::IProxy& proxy)
        : proxy_(proxy)
    {
    }

    ~Wired_proxy() = default;

public:
    std::string HwAddress()
    {
        return proxy_.getProperty("HwAddress").onInterface(INTERFACE_NAME);
    }

    std::string PermHwAddress()
    {
        return proxy_.getProperty("PermHwAddress").onInterface(INTERFACE_NAME);
    }

    uint32_t Speed()
    {
        return proxy_.getProperty("Speed").onInterface(INTERFACE_NAME);
    }

    std::vector<std::string> S390Subchannels()
    {
        return proxy_.getProperty("S390Subchannels").onInterface(INTERFACE_NAME);
    }

    bool Carrier()
    {
        return proxy_.getProperty("Carrier").onInterface(INTERFACE_NAME);
    }

private:
    sdbus::IProxy& proxy_;
};

}}}} // namespaces

#endif
