
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp__dbus_hpp_org_freedesktop_NetworkManager_Device_Statistics_hpp__proxy__H__
#define __sdbuscpp__dbus_hpp_org_freedesktop_NetworkManager_Device_Statistics_hpp__proxy__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace org {
namespace freedesktop {
namespace NetworkManager {
namespace Device {

class Statistics_proxy
{
public:
    static constexpr const char* INTERFACE_NAME = "org.freedesktop.NetworkManager.Device.Statistics";

protected:
    Statistics_proxy(sdbus::IProxy& proxy)
        : proxy_(proxy)
    {
    }

    ~Statistics_proxy() = default;

public:
    uint32_t RefreshRateMs()
    {
        return proxy_.getProperty("RefreshRateMs").onInterface(INTERFACE_NAME);
    }

    void RefreshRateMs(const uint32_t& value)
    {
        proxy_.setProperty("RefreshRateMs").onInterface(INTERFACE_NAME).toValue(value);
    }

    uint64_t TxBytes()
    {
        return proxy_.getProperty("TxBytes").onInterface(INTERFACE_NAME);
    }

    uint64_t RxBytes()
    {
        return proxy_.getProperty("RxBytes").onInterface(INTERFACE_NAME);
    }

private:
    sdbus::IProxy& proxy_;
};

}}}} // namespaces

#endif
