
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp__dbus_hpp_org_freedesktop_NetworkManager_WiMax_Nsp_hpp__proxy__H__
#define __sdbuscpp__dbus_hpp_org_freedesktop_NetworkManager_WiMax_Nsp_hpp__proxy__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace org {
namespace freedesktop {
namespace NetworkManager {
namespace WiMax {

class Nsp_proxy
{
public:
    static constexpr const char* INTERFACE_NAME = "org.freedesktop.NetworkManager.WiMax.Nsp";

protected:
    Nsp_proxy(sdbus::IProxy& proxy)
        : proxy_(proxy)
    {
    }

    ~Nsp_proxy() = default;

public:
    std::string Name()
    {
        return proxy_.getProperty("Name").onInterface(INTERFACE_NAME);
    }

    uint32_t SignalQuality()
    {
        return proxy_.getProperty("SignalQuality").onInterface(INTERFACE_NAME);
    }

    uint32_t NetworkType()
    {
        return proxy_.getProperty("NetworkType").onInterface(INTERFACE_NAME);
    }

private:
    sdbus::IProxy& proxy_;
};

}}}} // namespaces

#endif
