
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp__dbus_hpp_org_freedesktop_NetworkManager_Device_Modem_hpp__proxy__H__
#define __sdbuscpp__dbus_hpp_org_freedesktop_NetworkManager_Device_Modem_hpp__proxy__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace org {
namespace freedesktop {
namespace NetworkManager {
namespace Device {

class Modem_proxy
{
public:
    static constexpr const char* INTERFACE_NAME = "org.freedesktop.NetworkManager.Device.Modem";

protected:
    Modem_proxy(sdbus::IProxy& proxy)
        : proxy_(proxy)
    {
    }

    ~Modem_proxy() = default;

public:
    uint32_t ModemCapabilities()
    {
        return proxy_.getProperty("ModemCapabilities").onInterface(INTERFACE_NAME);
    }

    uint32_t CurrentCapabilities()
    {
        return proxy_.getProperty("CurrentCapabilities").onInterface(INTERFACE_NAME);
    }

    std::string DeviceId()
    {
        return proxy_.getProperty("DeviceId").onInterface(INTERFACE_NAME);
    }

    std::string OperatorCode()
    {
        return proxy_.getProperty("OperatorCode").onInterface(INTERFACE_NAME);
    }

    std::string Apn()
    {
        return proxy_.getProperty("Apn").onInterface(INTERFACE_NAME);
    }

private:
    sdbus::IProxy& proxy_;
};

}}}} // namespaces

#endif
